"use client";

import type { Metadata, Viewport } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import SplashScreen from "@/app/ui/splash-screen";
import { useState, useEffect } from "react";

const inter = Mulish({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    setTimeout(() => {
      setIsLoading(false);
    }, 1000);
  }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SplashScreen />
        {/* {isLoading ? <SplashScreen /> : children} */}
      </body>
    </html>
  );
}
