import type { Metadata, Viewport } from 'next';
import { Mulish } from 'next/font/google';
import SplashScreen from '@/app/ui/splash-screen';

import './globals.css';

const inter = Mulish({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SplashScreen />
        {children}
      </body>
    </html>
  );
}
