import { ReactNode } from 'react';
import type { Metadata, Viewport } from 'next';

import { mulish } from '@/app/fonts';
import SplashScreen from '@/app/components';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const viewport: Viewport = {
  initialScale: 1,
  width: 'device-width',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <SplashScreen />
        {children}
      </body>
    </html>
  );
}
